FROM --platform=linux/amd64 amalayan/qbittorrentvpn:latest

# Apply Synology kernel 3.10 modifications.  Only use for amd64 platform
ADD synology_3.10/syno-modifications.sh /tmp/syno-modifications.sh
RUN bash -c "chmod +x /tmp/syno-modifications.sh; /tmp/syno-modifications.sh" \
    && apt-get clean \
    && apt --purge autoremove -y \
    && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*